minizip: install missing `ints.h` header
Without the change the `gtwebengine` fails to buil as:

    /nix/store/...-minizip-1.3.2/include/minizip/ioapi.h:74:10: fatal error: ints.h: No such file or directory
       74 | #include "ints.h"
          |          ^~~~~~~~